[WIP] #22: Taxonomy Sitemaps
GoogleChromeLabs/wp-sitemaps pull request #62
Opened 2019-11-12 16:53 UTC by kirstyburgoine

### Issue Number
https://github.com/GoogleChromeLabs/wp-sitemaps/issues/22
This WIP still. Blocked by https://github.com/GoogleChromeLabs/wp-sitemaps/pull/58

### Description
Refactors the categories sitemaps work to generate sitemaps for all taxonomies

### Screenshots (before and after if applicable)
If your PR includes visual changes include before and after screenshots showing the change.

### Type of change
Please select the relevant options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (change which improves an existing feature. E.g., performance improvement, docs update, etc.)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Steps to test
Describe the tests required to verify your changes.
Provide instructions so the PR Tester can check functionality and also list any relevant details and / or dependencies required for your tests.

### Acceptance criteria
- [ ] My code follows WordPress coding standards.
- [ ] I have performed a self-review of my own code.
- [ ] If the changes are visual, I have cross-browser / device tested.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added test instructions that prove my fix is effective or that my feature works.

2019-11-13 17:40 UTC, kirstyburgoine commented on inc/class-core-sitemaps-taxonomies.php
> +				$taxonomy_terms = get_terms(
This may need changing to use `new WP_Term_Query` instead so that `$paged` parameter can be used still.

2019-11-13 17:40 UTC, kirstyburgoine commented on inc/class-core-sitemaps-taxonomies.php
> +						'hide_empty' => true,
also need to use `CORE_SITEMAPS_POSTS_PER_PAGE` in this array

2019-11-13 17:42 UTC, kirstyburgoine commented on inc/class-core-sitemaps-taxonomies.php
> +							'tax_query'      => array(
This is causing `WARNING | Detected usage of tax_query, possible slow query.` in phpcs so may need changing to something more performant?

2019-11-13 17:49 UTC, kirstyburgoine commented on inc/class-core-sitemaps-taxonomies.php
> +							'tax_query'      => array(
Probably need to improve general performance here as well based on: https://github.com/GoogleChromeLabs/wp-sitemaps/pull/55

2019-11-13 20:03 UTC, joemcgill requested changes

2019-11-13 20:03 UTC, joemcgill commented on inc/class-core-sitemaps-taxonomies.php
> +		if ( ! isset( $sub_types[ $sub_type ] ) ) {
This will cause all pages on the front end to 404 because this `render_sitemap()` callback gets fired on every `template_redirect` action. All of the logic for handling these sitemaps should happen after the initial `$this->slug === $sitemap` check.

2019-11-13 20:03 UTC, joemcgill commented on inc/class-core-sitemaps-taxonomies.php
> +		if ( empty( $type ) ) {
I don't think we ever actually want this fallback behavior. The function should probably fail if this happens for taxonomies.

2019-11-13 20:03 UTC, joemcgill commented on inc/class-core-sitemaps-taxonomies.php
> +							'tax_query'      => array(
Yeah, this could end up being really slow. Let's add the following args to the `get_posts()` args to ensure we're only doing a single DB hit for each term:

```
'no_found_rows' => true,
'update_post_term_cache' => false,
'update_post_meta_cache' => false,
```

We may need to revisit this later to make it more performant.

2019-11-14 10:59 UTC, svandragt reviewed
Looking good!

2019-11-14 16:38 UTC, joemcgill requested changes
Changes look good. I somehow left out one bit of review feedback that I'd though I had left yesterday. Once that's addressed, this is ready to go in.

2019-11-14 16:38 UTC, joemcgill commented on inc/class-core-sitemaps-taxonomies.php
> +		foreach ( $taxonomies as $taxonomy ) {
I thought I'd already mentioned this, but I must have forgotten to add the comment. 

I don't think this loop is necessary in this method. I'd prefer to assume that validation for the sub-type is handled in the `render_sitemaps()` method so you can run the term query directly using `$this->sub_type` as the `'taxonomy'` argument.

2019-11-14 18:18 UTC, joemcgill approved these changes
Looks good. Thanks!

2019-11-14 21:03 UTC, merged